### ISSUE TITLE
Almacenamiento incorrecto posición de entidades

### ISSUE THREAD

**Issue by gegianno** [LemontechSA/limoneno#16]
Al etiquetar una entidad se almacena el nombre de esta, la posición de su caracter inicial y la posición de su caracter final. El problema es que la posición final se encuentra desplazada en un caracter.

Es necesario investigar por qué ocurre esto, y solucionarlo.

**Comment by EmanuelCadems** [comment]
Seguramente hay que sumarle 1, porque en python la selección se hace desde el inicio hasta el caracter siguiente al que querés elegir. Ej 
```py
"hola mundo"[0:4]
'hola'
```
A diferencia de ruby:
```ruby
"hola mundo"[0..3]
=> "hola"
```

**Comment by ameboide** [comment]
Aprovecho de hacer una sugerencia: al seleccionar el texto se puede fallar por un caracter, o incluir o no un espacio o puntuación. Podríamos hacer que el inicio y final se ajusten a las palabras seleccionadas. Acá va una implementación de ejemplo:
```javascript
function ajustar(s, desde, hasta){
  console.log(`original: (${desde}..${hasta}) = "${s.substr(desde, hasta - desde + 1)}"`);
  
  if(s.substr(desde - 1, 2).match(/\w\w/)){
    // parte entremedio de una palabra, retrocedo hasta el comienzo de la palabra
    for(desde--; desde>0 && s[desde].match(/\w/); desde--);
  } else if(s[desde].match(/\W/)){
    // parte en un caracter no-palabra, avanzo hasta el comienzo de una palabra
    for(desde++; desde<hasta && s[desde].match(/\W/); desde++);
  }
  
  if(s.substr(hasta, 2).match(/\w\w/)){
    // termina entremedio de una palabra, avanzo hasta el fin de la palabra
    for(hasta++; hasta<s.length && s[hasta+1].match(/\w/); hasta++);
  } else if(s[hasta].match(/\W/)){
    // termina en un caracter no-palabra, retrocedo hasta el fin de una palabra
    for(hasta--; hasta>0 && s[hasta].match(/\W/); hasta--);
  }

  console.log(`nuevo: (${desde}..${hasta}) = "${s.substr(desde, hasta - desde + 1)}"`);
  return [desde, hasta];
}
let s='esto es una prueba de concepto';
ajustar(s, 4, 8);
ajustar(s, 1, 7);
/*
original: (4..8) = " es u"
nuevo: (5..10) = "es una"
original: (1..7) = "sto es " 
nuevo: (0..6) = "esto es"
*/
```

**Comment by gegianno** [comment]
>Seguramente hay que sumarle 1

Buena teoría, pero lo revisé bien y está quedando un caracter extra al final, no es por el lenguaje. Debe tener que ver con el bug no corregido en que todavía hay problemas para etiquetar hasta el último caracter de un documento, debe haber un índice corrido.


>Aprovecho de hacer una sugerencia

Muy de acuerdo con esta idea, va a ayudar a estandarizar las entidades y mejorar la data.

**Comment by ameboide** [comment]
Esto debería haber quedado corregido con #19
